# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accounts_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import QSize, QRect, Qt, QCoreApplication
from PyQt5.QtWidgets import (
    QWidget,
    QSizePolicy,
    QGroupBox,
    QLabel,
    QScrollArea,
    QFrame,
    QVBoxLayout,
    QListWidget,
    QAbstractItemView,
    QListWidgetItem,
    QFormLayout,
    QLineEdit,
    QPushButton,
    QCheckBox,
)

class QAccountPanel(QWidget):
    def __init__(self, parent=None):
        super(QAccountPanel, self).__init__(parent)

        sizepolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Preferred)
        sizepolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setMinimumSize(QSize(175, 0))
        self.setSizePolicy(sizepolicy)
        self.setObjectName("accounts_panel")

        self.main_layout = QVBoxLayout(self)
        self.main_layout.setContentsMargins(0, 0, 0, 0)

        # Scrollable area
        self.scroll_area = QScrollArea()
        self.scroll_area.setWidgetResizable(True)
        # self.scroll_area.setGeometry(QRect(0, 0, 175, 500))
        self.scroll_area.setFrameShape(QFrame.NoFrame)
        self.scroll_area.setFrameShadow(QFrame.Plain)
        self.scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setAlignment(Qt.AlignCenter)
        self.scroll_area.setObjectName("scroll_area")

        self.scroll_area_content = QWidget()
        self.scroll_area_content.setObjectName("scroll_area_content")
        self.scroll_area_layout = QVBoxLayout(self.scroll_area_content)
        self.scroll_area_layout.setContentsMargins(0, 0, 0, 0)

        # Accounts Group
        self.accounts_group = QGroupBox("Accounts")
        self.accounts_group.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.accounts_group.setObjectName("accounts_group")
        self.accounts_layout = QVBoxLayout(self.accounts_group)
        self.accounts_layout.setContentsMargins(0, 0, 0, 0)
        self.accounts_layout.setObjectName("accounts_layout")

        # List of Accounts
        self.accounts_list = QListWidget()
        self.accounts_list.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.accounts_list.setAlternatingRowColors(True)
        self.accounts_list.setSortingEnabled(True)
        self.accounts_list.setObjectName("accounts_list")
        ########## Load in Accounts Here
        item = QListWidgetItem("template (default)")
        self.accounts_list.addItem(item)
        self.accounts_layout.addWidget(self.accounts_list)

        # Account Editing Layout
        self.form_layout = QFormLayout()
        self.form_layout.setContentsMargins(5, 0, 5, 0)
        self.form_layout.setVerticalSpacing(2)
        self.form_layout.setObjectName("form_layout")
        self.name_label = QLabel()
        self.name_label.setText("Name")
        self.name_label.setObjectName("name_label")
        self.form_layout.setWidget(0, QFormLayout.LabelRole, self.name_label)
        self.name_edit = QLineEdit()
        self.name_edit.setObjectName("name_edit")
        self.form_layout.setWidget(0, QFormLayout.FieldRole, self.name_edit)
        self.ip_label = QLabel()
        self.ip_label.setText("IP")
        self.ip_label.setObjectName("ip_label")
        self.form_layout.setWidget(1, QFormLayout.LabelRole, self.ip_label)
        self.ip_edit = QLineEdit()
        self.ip_edit.setObjectName("ip_edit")
        self.form_layout.setWidget(1, QFormLayout.FieldRole, self.ip_edit)
        self.accounts_layout.addLayout(self.form_layout)

        # Account Buttons
        self.form_button_layout = QVBoxLayout()
        self.form_button_layout.setSpacing(0)
        self.form_button_layout.setObjectName("form_button_layout")

        self.save_button = QPushButton("Save")
        self.save_button.setObjectName("save_button")
        self.save_button.setEnabled(False)
        self.delete_button = QPushButton("Delete")
        self.delete_button.setObjectName("delete_button")
        self.delete_button.setEnabled(False)
        self.create_new_button = QPushButton("Create")
        self.create_new_button.setObjectName("create_new_button")
        self.set_default_button = QPushButton("Set as Default")
        self.set_default_button.setObjectName("set_default_button")
        self.set_default_button.setEnabled(False)

        self.form_button_layout.addWidget(self.save_button)
        self.form_button_layout.addWidget(self.delete_button)
        self.form_button_layout.addWidget(self.create_new_button)
        self.form_button_layout.addWidget(self.set_default_button)

        # Adding all Layouts Together
        self.accounts_layout.addLayout(self.form_button_layout)
        self.accounts_group.setLayout(self.accounts_layout)

        self.scroll_area_layout.addWidget(self.accounts_group)
        self.scroll_area_content.setLayout(self.scroll_area_layout)
        self.scroll_area.setWidget(self.scroll_area_content)

        self.main_layout.addWidget(self.scroll_area)
        self.setLayout(self.main_layout)